web/router.ex
defmodule OhalaClassifieds.Router do
  use OhalaClassifieds.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession # looks in the session for the token
    plug Guardian.Plug.LoadResource
    plug OhalaClassifieds.CurrentUser
  end

  pipeline :authentication_required do
    plug Guardian.Plug.EnsureAuthenticated,
    handler: OhalaClassifieds.GuardianErrorHandler
  end

  pipeline :backend_authentication_required do
    plug OhalaClassifieds.CheckAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader # Looks in the Authorization header for the token
    plug Guardian.Plug.LoadResource
  end

  scope "/", OhalaClassifieds do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/", PageController, :index
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    resources "/login", SessionController, only: [:new, :create, :delete]
    get "/ads", AdsController, :ads
    get "/ad/:id", AdsController, :view_ad


    # registered user zone
    scope "/" do
      pipe_through [:authentication_required]
      resources "/user", UserController, only: [:show]
      resources "/ads", AdsController

      # member zone
      scope "/member", Member, as: :member do
        pipe_through []
        resources "/user", UserController do
          resources "/ads", AdsController
        end
      end

      # backend zone
      scope "/backend", Backend, as: :backend do
        pipe_through [:backend_authentication_required]
        get "/user/:user_id/user_role/:role_id/edit", UserController, :edit_user_role
        put "/user/:user_id/user_role/:role_id", UserController, :update_user_role
        get "/user/:user_id/trigger", UserController, :trigger_action
        resources "/user", UserController do
          resources "/ads", AdsController
        end
      end
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", OhalaClassifieds do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule OhalaClassifieds.LayoutView do
  use OhalaClassifieds.Web, :view

  def user_signed_in?(conn) do
    !!conn.assigns.current_user
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello OhalaClassifieds!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

  <div class="container">
    <div class="header">

      <ol class="breadcrumb text-right">

        <li class="pull-left">
          <%= link "Home", to: "/" %>
        </li>

        <li class="pull-left">
          <%= link "All Ads", to: ads_path(@conn, :ads) %>
        </li>

        <%= if @current_user do %>

          <%= for role <- @current_user.roles do %>

            <%= if role.name == "backend" do %>
              <li class="pull-left">
                <%= link "Users", to: backend_user_path(@conn, :index) %>
              </li>
            <% end %>

            <%= if role.name == "admin" do %>
              <li class="pull-left">
                <%= link "My Ads", to: member_user_ads_path(@conn, :index, @current_user) %>
              </li>
            <% end %>

          <% end %>

          <span>
            <%= link @current_user.email, to: user_path(@conn, :show, @current_user) %>
          </span>
          <li>&nbsp;</li>
          <li>
            <%= link "Sign Out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
          </li>

        <% else %>

          <span><%= link "Sign In", to: session_path(@conn, :new) %></span>
          <li>&nbsp;</li>
          <li><%= link "Register", to: registration_path(@conn, :new) %></li>

        <% end %>

      </ol>

    </div>

  </div>

  <div class="container">
    <header class="header">
      <span class="logo"></span>
    </header>

    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  </div> <!-- /container -->
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>